let paragraphElement = document.querySelector('p');

function changeParagraphText() {
    paragraphElement.textContent = "Clicked!";
}

paragraphElement.addEventListener('click', changeParagraphText);

let inputElement = document.querySelector('input');

// Event object is generated by the browser for each event on the tab
function retrieveUserInput(event) {
    // let enteredText = inputElement.value;
    let enteredText = event.target.value;
    // let enteredText = event.data; <= This is different
    console.log(enteredText);
    // console.log(event);
}

inputElement.addEventListener('input', retrieveUserInput)