const inputElement = document.getElementById("prod-name");
const remainingCharsElement = document.getElementById("remaining-chars");
const maxAllowedChars = inputElement.maxLength;

// Event object is generated by the browser for each event on the tab
function updateRemainingCharacters(event) {
  const enteredText = event.target.value;
  const remainingChars = maxAllowedChars - enteredText.length;
  remainingCharsElement.textContent = remainingChars;

  if (remainingChars === 0) {
    remainingCharsElement.classList.add("error");
    inputElement.classList.add("error");
  } else if (remainingChars <= 10) {
    remainingCharsElement.classList.add("warning");
    inputElement.classList.add("warning");
    remainingCharsElement.classList.remove("error");
    inputElement.classList.remove("error");
  } else {
    remainingCharsElement.classList.remove("warning", "error");
    inputElement.classList.remove("warning", "error");
  }
}

inputElement.addEventListener("input", updateRemainingCharacters);
